# syntax=docker/dockerfile:1
FROM golang:1.19
WORKDIR /app
COPY go.mod g.sum ./
RUN go mod download
COPY *.go ./
RUN go build -o ./out/dist .
# RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping
EXPOSE 8080
CMD ["/go-live"]